export const tags = [
    'engineering',
    'robotics',
    'AI',
    'cybernetics',
    'Web design',
    'Mobile applications',
    'Fintech',
    'cybersecurity',
    'cryptography',
    'sustainability',
    'waste management',
    'agriculture',
    'programming',
    'designing',
    'fitness',
    'social-impact',
    'computer-vision',
    'software',
    'human-computer-interface',
    'Product Design',
    'Neuroscience',
    'Signal Processing',
    'Wearable Computing',
    'Open source',
    'Hardware',
    'Business',
    'Research',
    'Entrepreneurship',
    'Bioengineering',
    'Art',
    'Operating Systems',
    'Advanced Networks',
    'Distributed Systems',
    'Internet of Thigns',
    'Graphics'
]

export const skills = [
    'ReactJS',
    'NextJS',
    'React Native/Flutter',
    'TypeScript/JavaScript',
    'web3.js',
    'ThreeJS',
    'NodeJS',
    'Firebase',
    'Solidity',
    'Postgresql',
    'Rust',
    'Figma',
    'Docker',
    'Gitlab CI/CD',
    'Linux',
    'Python',
    'MongoDB',
    'Redis',
    'Data Structures and Algorithms',
    'Product Design',
    'UX Design',
    'User research',
    'System Design',
    'Scrum master',
]